name: Clean up and deploy docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  cleanup:
    name: Cleanup prior deployments
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Delete deployments
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages
          onlyRemoveDeployments: true
          
  docs:
    needs: cleanup
    permissions:
      contents: 'write'
      pages: 'write'
      id-token: 'write'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    name: Generate and publish the docs
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Dotnet Setup
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - run: dotnet tool update -g docfx
    - run: docfx docfx.json
        
    - uses: maxheld83/ghpages@master
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: _site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.GITHUB_TOKEN }} # See https://github.com/maxheld83/ghpages
